name: CI for Terraform

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: download Terraform
      run: wget https://releases.hashicorp.com/terraform/0.12.25/terraform_0.12.25_linux_amd64.zip
    - name: unzip Terraform
      run: unzip terraform_0.12.25_linux_amd64.zip
    - name: test Terraform
      run: terraform -version
    - name: terraform init
      run: terraform init
    - name: validate
      run: terraform validate
